version: '3.8'

services:
  portainer:
    container_name: portainer
    image: portainer/portainer-ce:latest
    command: -H unix:///var/run/docker.sock
    restart: always
    ports:
      - '8000:8000'
      - '9443:9443'
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
      - 'portainer-data:/data'
    networks:
      - private

networks:
  private:
    name: 'private'
    driver: bridge

volumes:
  portainer-data:
    driver: local
